language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings-test
node_js:
  - 12
before_script:
  - psql -c 'create database greetings-test;' -U postgres
  - psql -U postgres -d greetings-test -a -f greet-database.sql
services:
  - postgresql
# addons:
#   postgresql: '9.4'
#   apt:
#     packages:
#       - postgresql-server-dev-9.4